CREATE TABLE FOLIO(
    FOLIO_NO VARCHAR(100) NOT NULL,
    AMC VARCHAR(150) NOT NULL,
    FOLIO_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    PRIMARY KEY (FOLIO_ID)
);


CREATE TABLE SCHEME(
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    ADVISOR VARCHAR(50) DEFAULT '',
    FOLIO_ID INTEGER NOT NULL,
    ISIN VARCHAR(50) NOT NULL PRIMARY KEY,
    FOREIGN KEY (FOLIO_ID) REFERENCES FOLIO ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS(
    TRANSACTION_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TRANSACTION_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(200),
    TYPE VARCHAR(50),
    AMOUNT DOUBLE PRECISION,
    UNITS DOUBLE PRECISION,
    NAV DOUBLE PRECISION,
    BALANCE DOUBLE PRECISION,
    DIVIDEND_RATE DOUBLE PRECISION DEFAULT 0.0,
    ISIN VARCHAR(50) NOT NULL,
    FOREIGN KEY (ISIN) REFERENCES SCHEME ON DELETE CASCADE
);